### PR TITLE
IPv6 address parser improvements (PR #57905)

### PR DESCRIPTION
**Pull request by snimmagadda**
http://gnats.netbsd.org/cgi-bin/query-pr-single.pl?number=57905

### CODE REVIEW

**Comment by zoulasc** [comment]
There was a similar patch prior to this in the NetBSD gnats which I committed. Please let me know if you still have issues.

**Comment by markvuw** [comment]
I think you applied Sunil's original patch which didn't have the set port to "*" (FSTAR) fix.

**Comment by snimmagadda** [comment]
> There was a similar patch prior to this in the NetBSD gnats which I committed. Please let me know if you still have issues.

It's the same patch, since I wasn't sure if gnats PR suffices or this is the canonical upstream and did a pull-request here as well. As noted by @markvuw above, you missed this hunk from the patch...

		if (strlen(pstr) == 0)
			pstr = "*";

**Comment by zoulasc** [comment]
Ok, I have applied that part too.

christos

**Pull request closed without merging**
